language: "ar_model"

pipeline:
- name: "SpacyNLP"
- name: "lemma_farasa.FarasaLemmatizer"
- name: "SpacyTokenizer"
# - name: "token_lemma_farasa"
- name: "RegexFeaturizer"
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
# - name: "FarasaIntentLemmatizer"
- name: "SpacyFeaturizer"
- name: "SklearnIntentClassifier"

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    core_threshold: 0.5
    nlu_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
